Tum: derle calistir


derle:
	g++ -I ./include/ -o ./lib/Avl.o -c ./src/Avl.cpp
	g++ -I ./include/ -o ./lib/Stack.o -c ./src/Stack.cpp
	g++ -I ./include/ -o ./lib/StackNode.o -c ./src/StackNode.cpp
	g++ -I ./include/ -o ./bin/main ./lib/Avl.o ./lib/Stack.o ./lib/StackNode.o ./src/main.cpp

calistir:
	./bin/main